### ISSUE TITLE
'ValueError: numpy.ufunc has the wrong size, try recompiling' when install pyxDamerauLevenshtein

### ISSUE THREAD

**Issue by chemiron** [gfairchild/pyxDamerauLevenshtein#14] opened 2018-12-21 12:48 UTC
**How to reproduce:**
1. `docker run -it --entrypoint=/bin/bash python:3.6` to have a clean environment;
2. pip install numpy pyxdameraulevenshtein
3. call python
4. `>>> import pyxdameraulevenshtein`

**Result:** 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "__init__.pxd", line 885, in init pyxdameraulevenshtein
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

pyxDamerauLevenshtein==1.5

**Comment by gfairchild** [comment] 2018-12-21 21:34
I just tried to reproduce this using just a clean Python 3.7 virtual environment and did not get this error:

```
gfairchild@meow ~/Desktop> mkdir test
gfairchild@meow ~/Desktop> cd test/
gfairchild@meow ~/Desktop/test> pyvenv env
WARNING: the pyenv script is deprecated in favour of `python3.7 -m venv`
gfairchild@meow ~/Desktop/test> source env/bin/activate
(env) gfairchild@meow ~/Desktop/test> pip install numpy pyxdameraulevenshtein
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/3d/c3/a69406093c9a780a74964f41cd56b06c0346d686a9b3f392d123a663f5e0/numpy-1.15.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pyxdameraulevenshtein
  Using cached https://files.pythonhosted.org/packages/09/d8/77d02800d687ff8e12c8ec7b4ed917249fca27a1bccc6d24f0ac507a794c/pyxDamerauLevenshtein-1.5.tar.gz
Installing collected packages: numpy, pyxdameraulevenshtein
  Running setup.py install for pyxdameraulevenshtein ... done
Successfully installed numpy-1.15.4 pyxdameraulevenshtein-1.5
(env) gfairchild@meow ~/Desktop/test> pip list
Package               Version
--------------------- -------
numpy                 1.15.4
pip                   18.1
pyxDamerauLevenshtein 1.5
setuptools            39.0.1
(env) gfairchild@meow ~/Desktop/test> python
Python 3.7.1 (default, Nov 13 2018, 14:49:47)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyxdameraulevenshtein
>>>
```

However, when I attempt to run it in docker as you did, I get this:

```
gfairchild@meow ~/Desktop> docker run -it --entrypoint=/bin/bash python:3.6
Unable to find image 'python:3.6' locally
3.6: Pulling from library/python
54f7e8ac135a: Pull complete
d6341e30912f: Pull complete
087a57faf949: Pull complete
5d71636fb824: Pull complete
0c1db9598990: Pull complete
2eeb5ce9b924: Pull complete
a8c530378055: Pull complete
687ed2fb2a0d: Pull complete
620aea26e853: Pull complete
Digest: sha256:fc34d5b6cf5d00a6139a74370dc27ddc9ce18303e2210d0f199a6050cc29aa45
Status: Downloaded newer image for python:3.6
root@81731e880677:/# python --version
Python 3.6.7
root@81731e880677:/# pip install numpy pyxdameraulevenshtein
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/ff/7f/9d804d2348471c67a7d8b5f84f9bc59fd1cefa148986f2b74552f8573555/numpy-1.15.4-cp36-cp36m-manylinux1_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 981kB/s
Collecting pyxdameraulevenshtein
  Downloading https://files.pythonhosted.org/packages/09/d8/77d02800d687ff8e12c8ec7b4ed917249fca27a1bccc6d24f0ac507a794c/pyxDamerauLevenshtein-1.5.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 872kB/s
Building wheels for collected packages: pyxdameraulevenshtein
  Running setup.py bdist_wheel for pyxdameraulevenshtein ... done
  Stored in directory: /root/.cache/pip/wheels/fc/9d/35/1552693f1003d749cd7ea3d5d7ee3de6db98fb7094ce691e9c
Successfully built pyxdameraulevenshtein
Installing collected packages: numpy, pyxdameraulevenshtein
Successfully installed numpy-1.15.4 pyxdameraulevenshtein-1.5
root@81731e880677:/# pip list
Package               Version
--------------------- -------
numpy                 1.15.4
pip                   18.1
pyxDamerauLevenshtein 1.5
setuptools            40.6.2
wheel                 0.32.2
root@81731e880677:/# python
Python 3.6.7 (default, Nov 16 2018, 22:33:19)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyxdameraulevenshtein
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "__init__.pxd", line 885, in init pyxdameraulevenshtein
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```

I'm not quite sure what the difference is here. Something is going on inside the container that's not happening outside of it.

**Comment by chemiron** [comment] 2018-12-22 05:36
I think you didn't get the error on clean virtualenv because already had compiled version of NumPy, but the docker image was clean. I guess the main problem there is in `setup.py` since 1.4.1 works fine for the case above.

**Comment by gfairchild** [comment] 2018-12-22 05:41
Given the time of year, I unfortunately won't have time to fix this for a little while.  If you can wait, I'll try to revisit this in 1.5 weeks or so. Otherwise, I'd love to take a PR to fix this. I doubt the fix is very complicated, but I just don't have time to diagnose it right now.

**Comment by YosuaMichael** [comment] 2018-12-27 02:39
@chemiron I have gotten the same problem. If you need a quick fix my work around is to use python3.7 instead (somehow it works properly in python3.7).

Here what happen in python3.7:
```
➜  docker run -it --entrypoint=/bin/bash python:3.7-stretch
Unable to find image 'python:3.7-stretch' locally
3.7-stretch: Pulling from library/python
54f7e8ac135a: Already exists 
d6341e30912f: Already exists 
087a57faf949: Already exists 
5d71636fb824: Already exists 
0c1db9598990: Already exists 
bfb904e99f24: Pull complete 
3979c1f9d2e6: Pull complete 
b1551281985f: Pull complete 
39ab8f51abbe: Pull complete 
Digest: sha256:6ee9038175f7705c973da0128f0d0e77c5c5258916198690b6597b021870c7ba
Status: Downloaded newer image for python:3.7-stretch
root@585e2ae4998d:/# pip install numpy
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/38/39/f73e104d44f19a6203e786d5204532e214443ea2954917b27f3229e7639b/numpy-1.15.4-cp37-cp37m-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.9MB 1.4MB/s 
Installing collected packages: numpy
Successfully installed numpy-1.15.4
root@585e2ae4998d:/# pip install pyxdameraulevenshtein
Collecting pyxdameraulevenshtein
  Downloading https://files.pythonhosted.org/packages/09/d8/77d02800d687ff8e12c8ec7b4ed917249fca27a1bccc6d24f0ac507a794c/pyxDamerauLevenshtein-1.5.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 449kB/s 
Building wheels for collected packages: pyxdameraulevenshtein
  Running setup.py bdist_wheel for pyxdameraulevenshtein ... done
  Stored in directory: /root/.cache/pip/wheels/fc/9d/35/1552693f1003d749cd7ea3d5d7ee3de6db98fb7094ce691e9c
Successfully built pyxdameraulevenshtein
Installing collected packages: pyxdameraulevenshtein
Successfully installed pyxdameraulevenshtein-1.5
root@585e2ae4998d:/# python
Python 3.7.2 (default, Dec 26 2018, 08:43:08) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.version.version
'1.15.4'
>>> import pyxdameraulevenshtein
>>> 

```
We can import pyxdameraulevenshtein as expected :)

**Comment by pyk** [comment] 2018-12-27 04:17
@YosuaMichael btw, if you install the packages in one line

```
pip install numpy pyxdameraulevenshtein
```

the error can be reproduced:

```
% docker run -it --entrypoint=/bin/bash python:3.7-stretch
Unable to find image 'python:3.7-stretch' locally
3.7-stretch: Pulling from library/python
54f7e8ac135a: Pull complete 
d6341e30912f: Pull complete 
087a57faf949: Pull complete 
5d71636fb824: Pull complete 
0c1db9598990: Pull complete 
bfb904e99f24: Pull complete 
3979c1f9d2e6: Pull complete 
b1551281985f: Pull complete 
39ab8f51abbe: Pull complete 
Digest: sha256:6ee9038175f7705c973da0128f0d0e77c5c5258916198690b6597b021870c7ba
Status: Downloaded newer image for python:3.7-stretch
root@c3941698f186:/# pip install numpy pyxdameraulevenshtein
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/38/39/f73e104d44f19a6203e786d5204532e214443ea2954917b27f3229e7639b/numpy-1.15.4-cp37-cp37m-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.9MB 843kB/s 
Collecting pyxdameraulevenshtein
  Downloading https://files.pythonhosted.org/packages/09/d8/77d02800d687ff8e12c8ec7b4ed917249fca27a1bccc6d24f0ac507a794c/pyxDamerauLevenshtein-1.5.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 1.6MB/s 
Building wheels for collected packages: pyxdameraulevenshtein
  Running setup.py bdist_wheel for pyxdameraulevenshtein ... done
  Stored in directory: /root/.cache/pip/wheels/fc/9d/35/1552693f1003d749cd7ea3d5d7ee3de6db98fb7094ce691e9c
Successfully built pyxdameraulevenshtein
Installing collected packages: numpy, pyxdameraulevenshtein
Successfully installed numpy-1.15.4 pyxdameraulevenshtein-1.5
root@c3941698f186:/# python
Python 3.7.2 (default, Dec 26 2018, 08:43:08) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.version.version
'1.15.4'
>>> import pyxdameraulevenshtein
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "__init__.pxd", line 885, in init pyxdameraulevenshtein
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
>>> 
```

I think I should add the 

```
RUN pip install numpy 
```

in my Dockerfile before installing all the dependencies

**Comment by SharpEdgeMarshall** [comment] 2018-12-28 10:44
We debugged the issue, probably is caused by the fact that you have a fixed `numpy` version in your `requirements.txt` that differs from the latest that is used to build this package during `pip install -r requirements.txt`.
So you'll have a package built with the latest `numpy` and run with another version.

To demonstrate it just do:
- `pip uninstall pyxDamerauLevenshtein`
- `rm -rf ~/.cache/pip`
- `pip install pyxDamerauLevenshtein`
and it will start working again because it will build with your version of `numpy`

**Comment by simobasso** [comment] 2018-12-28 11:30
@gfairchild ⬆️ 😄

**Comment by simobasso** [comment] 2018-12-28 11:32
thanks @SharpEdgeMarshall

**Comment by gfairchild** [comment] 2019-01-04 23:36
A new version, 1.5.1, was just pushed to PyPI. This includes the fix found here. I also decided to simplify `setup.py` a bit. I've made the decision to expect the user to explicitly install NumPy *prior* to installing this library since that seemed to be causing a bunch of issues. 1.5.1 is now live on PyPI. Can you guys try and let me know if everything seems ok? It's working fine on my end:

```
> docker run -it --entrypoint=/bin/bash python:3.6
root@73bbd97506d7:/# pip install numpy pyxdameraulevenshtein
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/ff/7f/9d804d2348471c67a7d8b5f84f9bc59fd1cefa148986f2b74552f8573555/numpy-1.15.4-cp36-cp36m-manylinux1_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 1.2MB/s
Collecting pyxdameraulevenshtein
  Downloading https://files.pythonhosted.org/packages/6f/52/c0a0a6f0b5f85da31876f2055e34f9350e432f3f5821d247737f31c2cc0b/pyxDamerauLevenshtein-1.5.1.tar.gz (58kB)
    100% |████████████████████████████████| 61kB 15.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6nsoopjo/pyxdameraulevenshtein/setup.py", line 27, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6nsoopjo/pyxdameraulevenshtein/
root@73bbd97506d7:/# pip install numpy
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/ff/7f/9d804d2348471c67a7d8b5f84f9bc59fd1cefa148986f2b74552f8573555/numpy-1.15.4-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.15.4
root@73bbd97506d7:/# pip install pyxdameraulevenshtein
Collecting pyxdameraulevenshtein
  Using cached https://files.pythonhosted.org/packages/6f/52/c0a0a6f0b5f85da31876f2055e34f9350e432f3f5821d247737f31c2cc0b/pyxDamerauLevenshtein-1.5.1.tar.gz
Requirement already satisfied: numpy in /usr/local/lib/python3.6/site-packages (from pyxdameraulevenshtein) (1.15.4)
Building wheels for collected packages: pyxdameraulevenshtein
  Running setup.py bdist_wheel for pyxdameraulevenshtein ... done
  Stored in directory: /root/.cache/pip/wheels/45/dc/84/8b25030e662473c74f046d9b92ebc3803fcb6e20ce5e434687
Successfully built pyxdameraulevenshtein
Installing collected packages: pyxdameraulevenshtein
Successfully installed pyxdameraulevenshtein-1.5.1
root@73bbd97506d7:/# pip list
Package               Version
--------------------- -------
numpy                 1.15.4
pip                   18.1
pyxDamerauLevenshtein 1.5.1
setuptools            40.6.2
wheel                 0.32.2
root@73bbd97506d7:/# python
Python 3.6.7 (default, Nov 16 2018, 22:33:19)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyxdameraulevenshtein
>>>
```

**Comment by gfairchild** [comment] 2019-01-07 18:34
As discussed in #13, 1.5.2 was just pushed, which uses [PEP 518](https://www.python.org/dev/peps/pep-0518/) to install NumPy as a dependency prior to installation. This is working in the Docker use case above as well in a fresh virtual environment. No more hacky `setup.py` code!

**Comment by kootenpv** [comment] 2019-01-29 13:51
I'm still getting this issue with `1.5.2`. `numpy` has been installed before it, it's the last step in the build and I get the same error.

**Comment by gfairchild** [comment] 2019-01-29 16:05
What version of pip are you using? Try this:

```
pip install --upgrade pip
pip install pyxdameraulevenshtein
```

**Comment by simobasso** [comment] 2019-01-29 17:04
Hey @gfairchild,

the problem is not pip.

The problem is an unversioned numpy as setup requirement.

`requires` in your `pyproject.toml` (also `setup_requires` in `setup.py` before this pull request), satisfied dependencies *before* `pip` graph dependencies.

So if you have a `requirements.txt` like this:

```
numpy==1.14.2
pyxdameraulevenshtein==1.5.2
```

`pyxdameraulevenshtein` compile against the last version of numpy (1.16.0) which is incompatible with older versions of numpy **but** at runtime `pyxdameraulevenshtein` will try to use the installed numpy version (1.14.2 in this case).

**Comment by kootenpv** [comment] 2019-01-29 19:47
When I pinned `pyxDamerauLevenshtein==1.5` it was working... sounds like a regression.

**Comment by gfairchild** [comment] 2019-01-29 19:56
@kootenpv, can you show me the exact commands and output you get when trying to install?

**Comment by kootenpv** [comment] 2019-01-29 21:06
I was doing:

```python
RUN git clone https://github.com/RasaHQ/rasa_core.git  && \
    cd rasa_core                                       && \
    pip install -r requirements.txt                    && \
    pip install -e .

RUN pip install numpy==1.15.4

RUN pip install pyxDamerauLevenshtein
```

What is important I guess is that `rasa_core` pins `numpy==1.16.0`. 

I pretty much tried matching the numpy to what `pyxDamerauLevenshtein==1.5.2` is listing, but that did not work. I tried pretty much all combinations of numpy, pre and post install

What in the end worked was the above code, but instead of the last line:

```python
RUN pip install pyxDamerauLevenshtein==1.5
```

**Comment by gfairchild** [comment] 2019-01-30 07:01
Hm, I can't reproduce your error. I did essentially this:

```
RUN git clone https://github.com/RasaHQ/rasa_core.git  && \
    cd rasa_core                                       && \
    pip install -r requirements.txt                    && \
    pip install -e .

RUN pip install pyxDamerauLevenshtein
```

`rasa_core`'s `requirements.txt` file already installs NumPy 1.16.0, so I just installed pyxDamerauLevenshtein after it, and it worked just fine. You shouldn't need to manually install NumPy unless you're building from source (which you're not).

I can specify a version of NumPy in `pyproject.toml` and `setup.py`, but that shouldn't matter. `pyproject.toml` will just make sure that NumPy is installed, and if it's not, it'll grab the latest, and this should be sufficient.

Can you give me some more specifics about your environment? I've tested this on macOS, Windows (using the Linux subsystem), and Linux directly through Travis CI, and nothing fails.

**Comment by gfairchild** [comment] 2019-02-12 17:53
@kootenpv, are you able to provide a complete working example that I can use to reproduce this bug? I need a bit more information on how to reproduce this before it can be fixed.

**Comment by gfairchild** [comment] 2019-02-25 22:45
I found a way to reproduce this in Travis, and I think I've fixed it in 1.5.3, after reading @simobasso's post a little more carefully. I'm now specifying NumPy versions in `pyproject.toml` *and* `setup.py`.

I just pushed 1.5.3 to PyPI. @kootenpv, can you tell me if this fixes your issue?

**Comment by kootenpv** [comment] 2019-02-26 08:48
@gfairchild I have updated the version number for next build so we will see :-)

**Comment by gfairchild** [comment] 2019-03-04 06:19
I'm going to close this issue. Please let me know if you experience it again, and I can reopen.

**Closed by gfairchild** 2019-03-04 06:19 UTC

**Comment by kootenpv** [comment] 2019-03-07 16:40
@gfairchild Took some time to get to it (needed new credits, and a new build), but I can confirm 1.5.4 worked immediately for me.

**Comment by gfairchild** [comment] 2019-03-07 19:35
Wonderful! I'm glad to hear it.

**Comment by hkandpal** [comment] 2020-04-12 00:22
I have Python (Version 2.7 and 3.4) and Pandas installed on 
Amazon Linux AMI release 2018.03


[ec2-user@ip ~]$ python -V
Python 2.7.16
[ec2-user@ip ~]$ python3 -V
Python 3.5.7


[ec2-user@ip ~]$ pip3 list
Package         Version
--------------- --------
awscli          1.16.105
botocore        1.12.95
colorama        0.3.9
cx-Oracle       6.4.1
Cython          0.29.16
docutils        0.14
ez-setup        0.9
jmespath        0.9.3
numexpr         2.6.6
numpy           1.15.0
pandas          0.17.0
pip             20.0.2
pyasn1          0.4.5
python-dateutil 2.7.3
pytz            2018.5
PyYAML          3.13
rsa             3.4.2
s3transfer      0.2.0
setuptools      46.1.3
six             1.11.0
SQLAlchemy      1.2.10
tables          3.4.4
urllib3         1.24.1


[ec2-user@ip ~]$ python3
Python 3.5.7 (default, Feb 10 2020, 19:00:53)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> include pandas as pd
  File "<stdin>", line 1
    include pandas as pd
                 ^
SyntaxError: invalid syntax
>>>

Any idea why i get this error when using Python3 and Pandas.

thanks

**Comment by gfairchild** [comment] 2020-04-12 20:05
@hkandpal, I'm not sure how what you posted is relevant to pyxDamerauLevenshtein.
